server:
  port: 8084

spring:
  application:
    name: ahis-service

  datasource:
    url: jdbc:mysql://localhost:3306/ahis_db
    username: root
    password: yourpassword
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
